version: '2'

services:

  consul:
    image: consul:latest
    restart: always
    mem_limit: 128m
    ports:
      - 8501:8500
    command: agent -server -bootstrap-expect 1 -client 0.0.0.0 -ui

  gateway:
    image: ncornag/micro-docker-nginx
    restart: always
    mem_limit: 128m
    links:
      - consul:consul
    environment:
      - UPSTREAMUSEIP=true
    ports:
        - 80:80

  mongo:
    image: mongo:3
    ports:
      - 27018:27017
    volumes:
      - ./dockerConf/mongo/data:/data/db

  bus:
    image: rabbitmq:3-management
    ports:
      - 15673:15672
      - 5673:5672

  elasticsearch:
    image: elasticsearch:2
    ports:
      - 9201:9200
      - 9301:9300
    volumes:
      - ./dockerConf/elasticsearch/data:/usr/share/elasticsearch/data

  redis:
    image: redis:3
    ports:
      - 6380:6379

  logstash:
    image: logstash:2
    ports:
      - 12201:12201
      - 12201:12201/udp
    expose:
      - 5000
      - 12201
    volumes:
      - ./dockerConf/logstash:/config
    links:
      - elasticsearch
    command: logstash -f /config/logstash.conf

  kibana:
    image: kibana:4
    ports:
      - 5602:5601
    links:
      - elasticsearch
    depends_on:
      - elasticsearch

  stock-service:
    extends:
      file: docker-compose-common.yml
      service: service
    build: ./micro-stock-service
    links:
      - consul
      - gateway
      - bus
      - mongo
    depends_on:
      - mongo
      - bus

  catalog-service:
    extends:
      file: docker-compose-common.yml
      service: service
    build: ./micro-catalog-service
    links:
      - consul
      - gateway
      - mongo
      - bus
      - elasticsearch
    depends_on:
      - mongo
      - bus

  customer-service:
    extends:
      file: docker-compose-common.yml
      service: service
    build: ./micro-customer-service
    links:
      - consul
      - gateway
      - mongo
      - bus
      - elasticsearch
    depends_on:
      - mongo
      - bus

  cart-service:
    extends:
      file: docker-compose-common.yml
      service: service
    build: ./micro-cart-service
    links:
      - consul
      - gateway
      - bus
      - mongo
    depends_on:
      - mongo
      - bus

  tax-service:
    extends:
      file: docker-compose-common.yml
      service: service
    build: ./micro-tax-service
    links:
      - consul
      - gateway
      - bus
      - mongo
    depends_on:
      - mongo
      - bus

  promotion-service:
    extends:
      file: docker-compose-common.yml
      service: service
    build: ./micro-promotion-service
    links:
      - consul
      - gateway
      - bus
      - mongo
    depends_on:
      - mongo
      - bus

  recommendation-service:
    extends:
      file: docker-compose-common.yml
      service: service
    build: ./micro-recommendation-service
    links:
      - consul
      - gateway
      - bus
      - mongo
    depends_on:
      - mongo
      - bus
