FORMAT: 1A
HOST: http://localhost:3000

# Stock ecomm service
Ecommerce Stock service using micro-base framework (beta).

## Micro-base
Micro-base is a small framework to define and call services, and gives some basic utilities like config, logging, jobs and MongoDB access.
More info abot the framework [here](https://github.com/ncornag/micro-base/tree/develop).

# Data Structures
<!-- include(../../../../examples/micro-cart-service/src/docs/dataStructures.apib) -->
<!-- include(../../../../examples//micro-stock-service/src/docs/dataStructures.apib) -->
<!-- include(../../../../examples//micro-catalog-service/src/docs/dataStructures.apib) -->
# Group Cart Service
<!-- include(../../../../examples/micro-cart-service/src/docs/operations.apib) -->
# Group Stock Service
<!-- include(../../../../examples/micro-stock-service/src/docs/operations.apib) -->
# Group Catalog Service
<!-- include(../../../../examples/micro-catalog-service/src/docs/operations.apib) -->
