FORMAT: 1A
HOST: http://localhost:3000

# Stock ecomm service
Ecommerce Stock service using micro-base framework (beta).

## Micro-base
Micro-base is a small framework to define and call services, and gives some basic utilities like config, logging, jobs and MongoDB access.
More info abot the framework [here](https://github.com/ncornag/micro-base/tree/develop).

# Data Structures
<!-- include(../../services/micro-cart-service/src/docs/dataStructures.apib) -->
<!-- include(../../services/micro-stock-service/src/docs/dataStructures.apib) -->
# Group Cart
<!-- include(../../services/micro-cart-service/src/docs/operations.apib) -->
# Group Stock
<!-- include(../../services/micro-stock-service/src/docs/operations.apib) -->
